
package com.example.demo.wsdl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 3.0.0
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "TerytWs1", targetNamespace = "http://tempuri.org/", wsdlLocation = "https://uslugaterytws1test.stat.gov.pl/wsdl/terytws1.wsdl")
public class TerytWs1
    extends Service
{

    private final static URL TERYTWS1_WSDL_LOCATION;
    private final static WebServiceException TERYTWS1_EXCEPTION;
    private final static QName TERYTWS1_QNAME = new QName("http://tempuri.org/", "TerytWs1");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://uslugaterytws1test.stat.gov.pl/wsdl/terytws1.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        TERYTWS1_WSDL_LOCATION = url;
        TERYTWS1_EXCEPTION = e;
    }

    public TerytWs1() {
        super(__getWsdlLocation(), TERYTWS1_QNAME);
    }

    public TerytWs1(WebServiceFeature... features) {
        super(__getWsdlLocation(), TERYTWS1_QNAME, features);
    }

    public TerytWs1(URL wsdlLocation) {
        super(wsdlLocation, TERYTWS1_QNAME);
    }

    public TerytWs1(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, TERYTWS1_QNAME, features);
    }

    public TerytWs1(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TerytWs1(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ITerytWs1
     */
    @WebEndpoint(name = "custom")
    public ITerytWs1 getCustom() {
        return super.getPort(new QName("http://tempuri.org/", "custom"), ITerytWs1.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ITerytWs1
     */
    @WebEndpoint(name = "custom")
    public ITerytWs1 getCustom(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "custom"), ITerytWs1.class, features);
    }

    private static URL __getWsdlLocation() {
        if (TERYTWS1_EXCEPTION!= null) {
            throw TERYTWS1_EXCEPTION;
        }
        return TERYTWS1_WSDL_LOCATION;
    }

}
